package logica;

import interfaces.IControladorAgregarEspetaculoAPaqueteDeEspetaculos;

public class ControladorAgregarEspetaculoAPaqueteDeEspetaculos implements IControladorAgregarEspetaculoAPaqueteDeEspetaculos {

}
